# Logging Level
logging:
  level:
    root: info
    org.springframework: info
    com.tophelp.coworkbuddy: debug

# Actuator Security
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring:
# Datasource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=coworkbuddy
    username: postgres
    password: mysecretpassword
    # url: jdbc:postgresql://<uri>/<database>?currentSchema=<schema-name>
    # username: <user-name>
    # password: <password>
# Jpa - Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Flyway Configuration
  flyway:
    # url: jdbc:postgresql://<uri>/<database>
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    create-schemas: true
    default-schema: coworkbuddy

# Cloud

# Server Port Configuration
server:
  port: 80
